### ISSUE TITLE
Does not work anymore with xidlehook :(

### ISSUE THREAD

**Issue by CSRaghunandan** [rschmukler/xidlehook-caffeinate#1]
After running caffeinate, I can see that xidlehook is still locking the screen after the timeout. I even tried running it with a PID, but same issue. 

Any idea how to get it working again? I'm running xidlehook 0.8.2

**Comment by rschmukler** [comment]
Hey! xidlehook massively overhauled it's socket API in `0.8`. I haven't had time to update to the latest version, but I do intend to at some point. For now I'm sorry to say that my best answer is run an earlier version of xidlehook :(

**Comment by CSRaghunandan** [comment]
I see, thanks for your effort nonetheles :)

I will wait for you to make updates.
